Add support for querying by name
depscloud/depscloud pull request #116
Opened 2020-10-14 20:35 UTC by shinnlok

Fixes #100

I wasn't exactly sure how to test.

2020-10-15 01:00 UTC, mjpitz requested changes
Alright. So this is close, but for this to work properly, we need to ensure `organziation` and `module` are set properly on the request. I would write a helper function that accepts a `*Module` or `*DependencyRequest`. If the name is set, do the parsing that you're doing on top to extract the organization / module and set the values appropriately on the request.

The nice thing is that this helps simplify some of the checks a bit more.

Otherwise, this is

2020-10-15 01:00 UTC, mjpitz commented on deps/internal/client/http_modules.go
>  func (m *httpModuleClient) ListSources(ctx context.Context, in *schema.Module, opts ...grpc.CallOption) (*tracker.ListSourcesResponse, error) {
The HTTP clients are more or less a dead code path. I wouldn't bother trying to update them.

2020-10-15 02:31 UTC, shinnlok commented
@mjpitz Ah that makes a lot more sense. Updated.

2020-10-15 03:00 UTC, mjpitz approved these changes
I think you have one bug, but otherwise, this changeset looks good to me.

2020-10-15 03:54 UTC, shinnlok commented on deps/internal/cmds/get/common.go
> +	"strings"
👍

2020-10-15 03:54 UTC, shinnlok commented on deps/internal/cmds/get/common.go
> +		return []string{"_", split[1]}
Oops. Thanks!

2020-10-16 00:03 UTC, mjpitz approved these changes

2020-10-16 00:04 UTC, merged

2020-10-16 00:05 UTC, mjpitz commented
@shinnlok Awesome! Thank you so much for all the hard work. Would you mind taking a pass over the documentation and updating the queries to use the -n flag instead of organization and module?

2020-10-16 01:05 UTC, shinnlok commented
@mjpitz done https://github.com/depscloud/deps.cloud/pull/74

I also noticed I missed one https://github.com/depscloud/depscloud/pull/118 while looking over the docs.